// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.17.3
// source: GO_TEMPLATE_SERVICE.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Параметры запросы для метода 1
type Method1Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arg11 string `protobuf:"bytes,1,opt,name=arg11,proto3" json:"arg11,omitempty"`  // Аргумент 1
	Arg12 bool   `protobuf:"varint,2,opt,name=arg12,proto3" json:"arg12,omitempty"` // Аргумент 2
}

func (x *Method1Request) Reset() {
	*x = Method1Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GO_TEMPLATE_SERVICE_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Method1Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Method1Request) ProtoMessage() {}

func (x *Method1Request) ProtoReflect() protoreflect.Message {
	mi := &file_GO_TEMPLATE_SERVICE_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Method1Request.ProtoReflect.Descriptor instead.
func (*Method1Request) Descriptor() ([]byte, []int) {
	return file_GO_TEMPLATE_SERVICE_proto_rawDescGZIP(), []int{0}
}

func (x *Method1Request) GetArg11() string {
	if x != nil {
		return x.Arg11
	}
	return ""
}

func (x *Method1Request) GetArg12() bool {
	if x != nil {
		return x.Arg12
	}
	return false
}

// Параметры ответа на запрос метода 1
type Method1Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Method1Response) Reset() {
	*x = Method1Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GO_TEMPLATE_SERVICE_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Method1Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Method1Response) ProtoMessage() {}

func (x *Method1Response) ProtoReflect() protoreflect.Message {
	mi := &file_GO_TEMPLATE_SERVICE_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Method1Response.ProtoReflect.Descriptor instead.
func (*Method1Response) Descriptor() ([]byte, []int) {
	return file_GO_TEMPLATE_SERVICE_proto_rawDescGZIP(), []int{1}
}

// Параметры запросы для метода 2
type Method2Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Arg21 string `protobuf:"bytes,1,opt,name=arg21,proto3" json:"arg21,omitempty"`  // Аргумент 1
	Arg22 uint64 `protobuf:"varint,2,opt,name=arg22,proto3" json:"arg22,omitempty"` // Аргумент 2
}

func (x *Method2Request) Reset() {
	*x = Method2Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GO_TEMPLATE_SERVICE_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Method2Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Method2Request) ProtoMessage() {}

func (x *Method2Request) ProtoReflect() protoreflect.Message {
	mi := &file_GO_TEMPLATE_SERVICE_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Method2Request.ProtoReflect.Descriptor instead.
func (*Method2Request) Descriptor() ([]byte, []int) {
	return file_GO_TEMPLATE_SERVICE_proto_rawDescGZIP(), []int{2}
}

func (x *Method2Request) GetArg21() string {
	if x != nil {
		return x.Arg21
	}
	return ""
}

func (x *Method2Request) GetArg22() uint64 {
	if x != nil {
		return x.Arg22
	}
	return 0
}

// Параметры ответа на запрос метода 1
type Method2Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []string `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"` // Результат ответа метода 2
}

func (x *Method2Response) Reset() {
	*x = Method2Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_GO_TEMPLATE_SERVICE_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Method2Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Method2Response) ProtoMessage() {}

func (x *Method2Response) ProtoReflect() protoreflect.Message {
	mi := &file_GO_TEMPLATE_SERVICE_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Method2Response.ProtoReflect.Descriptor instead.
func (*Method2Response) Descriptor() ([]byte, []int) {
	return file_GO_TEMPLATE_SERVICE_proto_rawDescGZIP(), []int{3}
}

func (x *Method2Response) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_GO_TEMPLATE_SERVICE_proto protoreflect.FileDescriptor

var file_GO_TEMPLATE_SERVICE_proto_rawDesc = []byte{
	0x0a, 0x19, 0x47, 0x4f, 0x5f, 0x54, 0x45, 0x4d, 0x50, 0x4c, 0x41, 0x54, 0x45, 0x5f, 0x53, 0x45,
	0x52, 0x56, 0x49, 0x43, 0x45, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72, 0x6f,
	0x74, 0x65, 0x69, 0x2e, 0x75, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x22, 0x3c, 0x0a, 0x0e, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x72, 0x67, 0x31, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x72, 0x67,
	0x31, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x67, 0x31, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x05, 0x61, 0x72, 0x67, 0x31, 0x32, 0x22, 0x11, 0x0a, 0x0f, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3c, 0x0a, 0x0e, 0x4d,
	0x65, 0x74, 0x68, 0x6f, 0x64, 0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x61, 0x72, 0x67, 0x32, 0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x72,
	0x67, 0x32, 0x31, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x72, 0x67, 0x32, 0x32, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x05, 0x61, 0x72, 0x67, 0x32, 0x32, 0x22, 0x2b, 0x0a, 0x0f, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x32, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x32, 0xaf, 0x01, 0x0a, 0x11, 0x47, 0x6f, 0x54, 0x65, 0x6d,
	0x70, 0x6c, 0x61, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0b,
	0x54, 0x65, 0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x31, 0x12, 0x1d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x65, 0x69, 0x2e, 0x75, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x74, 0x68,
	0x6f, 0x64, 0x31, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x65, 0x69, 0x2e, 0x75, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x31, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x0b, 0x54, 0x65,
	0x73, 0x74, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x32, 0x12, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x65, 0x69, 0x2e, 0x75, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x32, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x65,
	0x69, 0x2e, 0x75, 0x63, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x32,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0e, 0x5a, 0x0c, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_GO_TEMPLATE_SERVICE_proto_rawDescOnce sync.Once
	file_GO_TEMPLATE_SERVICE_proto_rawDescData = file_GO_TEMPLATE_SERVICE_proto_rawDesc
)

func file_GO_TEMPLATE_SERVICE_proto_rawDescGZIP() []byte {
	file_GO_TEMPLATE_SERVICE_proto_rawDescOnce.Do(func() {
		file_GO_TEMPLATE_SERVICE_proto_rawDescData = protoimpl.X.CompressGZIP(file_GO_TEMPLATE_SERVICE_proto_rawDescData)
	})
	return file_GO_TEMPLATE_SERVICE_proto_rawDescData
}

var file_GO_TEMPLATE_SERVICE_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_GO_TEMPLATE_SERVICE_proto_goTypes = []interface{}{
	(*Method1Request)(nil),  // 0: protei.uc.api.Method1Request
	(*Method1Response)(nil), // 1: protei.uc.api.Method1Response
	(*Method2Request)(nil),  // 2: protei.uc.api.Method2Request
	(*Method2Response)(nil), // 3: protei.uc.api.Method2Response
}
var file_GO_TEMPLATE_SERVICE_proto_depIdxs = []int32{
	0, // 0: protei.uc.api.GoTemplateService.TestMethod1:input_type -> protei.uc.api.Method1Request
	2, // 1: protei.uc.api.GoTemplateService.TestMethod2:input_type -> protei.uc.api.Method2Request
	1, // 2: protei.uc.api.GoTemplateService.TestMethod1:output_type -> protei.uc.api.Method1Response
	3, // 3: protei.uc.api.GoTemplateService.TestMethod2:output_type -> protei.uc.api.Method2Response
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_GO_TEMPLATE_SERVICE_proto_init() }
func file_GO_TEMPLATE_SERVICE_proto_init() {
	if File_GO_TEMPLATE_SERVICE_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_GO_TEMPLATE_SERVICE_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Method1Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GO_TEMPLATE_SERVICE_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Method1Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GO_TEMPLATE_SERVICE_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Method2Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_GO_TEMPLATE_SERVICE_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Method2Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_GO_TEMPLATE_SERVICE_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_GO_TEMPLATE_SERVICE_proto_goTypes,
		DependencyIndexes: file_GO_TEMPLATE_SERVICE_proto_depIdxs,
		MessageInfos:      file_GO_TEMPLATE_SERVICE_proto_msgTypes,
	}.Build()
	File_GO_TEMPLATE_SERVICE_proto = out.File
	file_GO_TEMPLATE_SERVICE_proto_rawDesc = nil
	file_GO_TEMPLATE_SERVICE_proto_goTypes = nil
	file_GO_TEMPLATE_SERVICE_proto_depIdxs = nil
}
